version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    restart: always
    ports:
      - 5432:5432
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    volumes:
      - ./docker/postgres.conf:/etc/postgresql/postgresql.conf